[package]
name = "rss_parser"
version = "0.1.0"
authors = ["Francesco <francesco@piva.online>"]

[dependencies]
rss = { version = "1.6.0", features = ["from_url"] }
chrono = "0.4"
reqwest = "0.9.3"
nom = "4.1.1"


