[package]
name = "rss_parser"
version = "0.1.0"
authors = ["Francesco <francesco@piva.online>"]

[dependencies]
rss = { version = "1.5.0", features = ["from_url"] }

[patch.crates-io]
rss = { git = 'https://github.com/chess-seventh/rss', branch = 'develop' }

